services:
  - type: web
    name: stationlodgemobi
    env: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
    routes:
      - type: rewrite
        source: /
        destination: /passo-fundo-ev.html
      - type: rewrite
        source: /gestao-carregadores
        destination: /gestao-carregadores.html
      - type: rewrite
        source: /gestao-carregadores.html
        destination: /gestao-carregadores.html
      - type: rewrite
        source: /*
        destination: /passo-fundo-ev.html
